### ISSUE TITLE
Comprehensive GUI support

### ISSUE THREAD

**Issue by Dabasan** [Dabasan/JOGLFramework#3]
I suppose it would be more practical if JOGLFWindow can have GUI components such as menus and buttons. 

One way I have in mind is to use Swing. I don't know very much about Swing, so I'm going to take a closer look at how things work with Swing. 

Another way is to use external GUI libraries. I found some libraries on GitHub:

- https://github.com/nifty-gui/nifty-gui
- https://github.com/SpinyOwl/legui
- https://github.com/ice1000/jimgui

Nifty GUI seems to support JOGL. And so this will be the first candidate for my framework's comprehensive GUI support if it's determined to use an external library.

**Comment by Dabasan** [comment]
I had a sudden whim to try Nifty GUI during a break. So I copied and pasted code from their repo. I just suffered from an avalanche of unknown exceptions but I finally made something that actually worked. It was just a screen and a layer with a short text inside, but I thought it had a great potential......

**Comment by Dabasan** [comment]
To support Nifty GUI, maybe all I need to do is add a protected method GetWindow() in JOGLFWindow and make accessible its GLWindow instance to derived classes? Then users are able to extend JOGLFWindow to create a window class that uses Nifty GUI inside.

**Comment by Dabasan** [comment]
I've tried to use Nifty GUI with my framework and I'm getting the following exceptions.
> org.xml.sax.SAXParseException; cvc-elt.1.a: 要素'nifty'の宣言が見つかりません。
> 	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
> 	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
> 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
> 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
> 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
> 	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2132)
> 	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:829)
> 	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.beginNode(DOMValidatorHelper.java:276)
> 	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:243)
> 	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:189)
> 	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:108)
> 	at java.xml/javax.xml.validation.Validator.validate(Validator.java:124)
> 	at de.lessvoid.nifty.loaderv2.NiftyLoader.validate(NiftyLoader.java:154)
> 	at de.lessvoid.nifty.loaderv2.NiftyLoader.validateNiftyXml(NiftyLoader.java:131)
> 	at de.lessvoid.nifty.Nifty.validateXml(Nifty.java:638)
> 	at de.lessvoid.nifty.Nifty.validateXml(Nifty.java:627)
> 	at com.daxie.testspace.joglf.v2.niftygui.NiftyGUIWindow.Init(NiftyGUIWindow.java:37)
> 	at com.daxie.joglf.gl.window.JOGLFWindow.init(JOGLFWindow.java:268)
> 	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
> 	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
> 	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
> 	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
> 	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
> 	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
> 	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
> 	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
> 	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
> 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
> 	at java.base/java.util.TimerThread.run(Timer.java:506)
> Exception in thread "main-FPSAWTAnimator#00-Timer0" com.jogamp.opengl.util.AnimatorBase$UncaughtAnimatorException: com.jogamp.opengl.GLException: Caught ThreadDeath: null on thread main-FPSAWTAnimator#00-Timer0
> 	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:92)
> 	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
> 	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
> 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
> 	at java.base/java.util.TimerThread.run(Timer.java:506)
> Caused by: com.jogamp.opengl.GLException: Caught ThreadDeath: null on thread main-FPSAWTAnimator#00-Timer0
> 	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
> 	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
> 	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
> 	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
> 	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
> 	... 4 more
> Caused by: java.lang.ThreadDeath
> 	at java.base/java.lang.Thread.stop(Thread.java:949)
> 	at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook$1.run(GLWindow.java:724)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook.shutdownRenderingAction(GLWindow.java:719)
> 	at jogamp.newt.WindowImpl.shutdown(WindowImpl.java:635)
> 	at jogamp.newt.WindowImpl.shutdownAll(WindowImpl.java:123)
> 	at jogamp.newt.DisplayImpl$1.run(DisplayImpl.java:74)
> 	at com.jogamp.nativewindow.NativeWindowFactory.shutdown(NativeWindowFactory.java:272)
> 	at com.jogamp.nativewindow.NativeWindowFactory$2$1.run(NativeWindowFactory.java:190)
> 	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by Dabasan** [comment]
It's considered an error in XML......?

**Comment by Dabasan** [comment]
Just a memo for myself to tackle it someday......

The error disappears if I remove nifty.validateXml(), but still nothing on the screen.
That may be because I'm using the programmable pipeline?

Below is what I've got so far.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://nifty-gui.sourceforge.net/nifty-1.3.xsd">
    <screen id="start">
        <panel id="panel_left" width="80%" height="100%" childLayout="vertical" backgroundColor="#0f08"/>
        <panel id="panel_right" width="20%" height="100%" childLayout="vertical" backgroundColor="#00f8"/>
        <panel id="panel_top_right1" width="100%" height="15%" childLayout="center" backgroundColor="#00f8"/>
        <panel id="panel_top_right2" width="100%" height="15%" childLayout="center" backgroundColor="#44f8"/>
        <panel id="panel_bot_right" width="100%" height="70%" valign="center" backgroundColor="#88f8"/>
    </screen>
</nifty>
```

```java
package com.daxie.testspace.joglf.v2.niftygui;

import com.daxie.joglf.gl.window.JOGLFWindow;
import com.jogamp.newt.opengl.GLWindow;

import de.lessvoid.nifty.Nifty;
import de.lessvoid.nifty.nulldevice.NullSoundDevice;
import de.lessvoid.nifty.render.batch.BatchRenderDevice;
import de.lessvoid.nifty.renderer.jogl.input.JoglInputSystem;
import de.lessvoid.nifty.renderer.jogl.render.JoglBatchRenderBackendCoreProfileFactory;
import de.lessvoid.nifty.spi.render.RenderDevice;
import de.lessvoid.nifty.spi.time.TimeProvider;

public class NiftyGUIWindow extends JOGLFWindow{
	public NiftyGUIWindow() {
		
	}

	private Nifty nifty;
	private JoglInputSystem input_system;
	private RenderDevice render_device;
	
	@Override
	protected void Init() {
		GLWindow window=this.GetWindow();
		render_device=new BatchRenderDevice(JoglBatchRenderBackendCoreProfileFactory.create(window));
		input_system=new JoglInputSystem(window);
		
		nifty=new Nifty(render_device, new NullSoundDevice(), input_system, new TimeProvider() {
			@Override
			public long getMsTime() {
				return System.currentTimeMillis();
			}
		});
		
		/*
		try {
			nifty.validateXml("./testwindow.xml");
		}
		catch(Exception e) {
			e.printStackTrace();
			System.exit(0);
		}
		*/
		
		nifty.fromXml("./testwindow.xml", "start");
	}
	@Override
	protected void Update() {
		nifty.update();
	}
	@Override
	protected void Draw() {
		nifty.render(true);
	}
}
```
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/C:/maven/repository/org/jogamp/gluegen/gluegen-rt/2.3.2/gluegen-rt-2.3.2.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
> WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 10月 09, 2019 10:54:50 午後 de.lessvoid.nifty.render.batch.core.CoreShader printLogInfo
> 情報: [16] Info log:
>
> 10月 09, 2019 10:54:50 午後 de.lessvoid.nifty.render.batch.core.CoreShader printLogInfo
> 情報: [16] Info log:
>
> 10月 09, 2019 10:54:50 午後 de.lessvoid.nifty.render.batch.core.CoreShader getUniform
> 情報: [16] glUniformLocation for [uTex] = [1]
> 10月 09, 2019 10:54:50 午後 de.lessvoid.nifty.render.batch.core.BatchRenderBackendCoreProfileInternal useHighQualityTextures
> 情報: Using low quality textures (no filtering).
> 10月 09, 2019 10:54:50 午後 de.lessvoid.nifty.render.batch.core.BatchRenderBackendCoreProfileInternal fillRemovedImagesInAtlas
> 情報: Not filling in removed images in atlas.
> 10月 09, 2019 10:54:50 午後 de.lessvoid.nifty.render.batch.BatchRenderDevice createTextureAtlas
> 情報: Created a new texture atlas (atlas texture id: 3).
> 10月 09, 2019 10:54:50 午後 de.lessvoid.nifty.render.batch.BatchRenderDevice nextTextureAtlas
> 情報: Switched atlases to atlas texture with id: 3.
> 10月 09, 2019 10:54:51 午後 de.lessvoid.nifty.loaderv2.types.ScreenType create
> 警告: Missing ScreenController for screen [start] using DefaultScreenController() instead but this might not be what you want.
> 10月 09, 2019 10:54:51 午後 de.lessvoid.nifty.render.batch.core.CoreShader getUniform
> 情報: [16] glUniformLocation for [uModelViewProjectionMatrix] = [0]

**Comment by Dabasan** [comment]
I've decided to give up this enhancement as it's more of a user issue.
It seems to be possible for users to assemble Nifty GUI as long as there's a certain way to get GLWindow.
There would be no need for further enhancement in my library.
